#!/bin/bash
#Author: https://github.com/zajac-h 

i_flag='' #install RustDedicated
u_flag='' #update 
r_flag='' #run
o_flag='' #install oxide (uMod)
h_flag='' #print help

print_usage() {
    echo "Usage:"
    echo "-i (--install) install Rust server"
    echo "-u (--update) update Rust server"
    echo "-r (--run) run Rust server"
    echo "-o (--oxide) install Oxide (uMod)"
    echo "-h (--help) print help"
}


while test $# -gt 0; do
    case "$1" in
        -i|--install) i_flag='true'                 && break ;;
        -u|--update) u_flag='true'                  && break ;;
        -r|--run) r_flag='true'                     && break ;;
        -o|--oxide) o_flag='true'                   && break ;;
        -h|--help) print_usage                      && exit 1 ;;
        *) echo "Unknown command." && print_usage   && exit 1 ;;
    esac
done


if [[ $i_flag == 'true' ]] ; then
    echo "Installing Rust server."

    mkdir SteamCMD && cd SteamCMD
    wget "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" && tar -zxf - || echo "Failed to download SteamCMD" ; exit 1
    ./steamcmd.sh +login anonymous +force_install_dir .. +app_update 258550 validate +quit
    cd ..

    echo "Installed succesfully."
fi


if [[ $u_flag == 'true' ]] ; then
    echo "Updating Rust server."

    cd SteamCMD || echo "Seems that SteamCMD is missing. Ensure that you have installed Rust server." ; exit 1
    ./steamcmd.sh +login anonymous +force_install_dir .. +app_update 258550 validate +quit
    cd ..

    echo "Updated succesfully."
fi

exit 0
