#!/bin/bash
#Author: https://github.com/zajac-h 

i_flag='' #install RustDedicated
u_flag='' #update 
r_flag='' #run
v_flag='' #validate install
o_flag='' #install oxide (uMod)
h_flag='' #print help

print_usage() {
    echo ""
    echo "Usage:"
    echo "  -i (--install) install Rust server"
    echo "  -u (--update) update Rust server"
    echo "  -r (--run) run Rust server"
    echo "  -v (--validate) validate install"
    echo "  -o (--oxide) install Oxide (uMod)"
    echo "  -h (--help) print help"
    echo ""
}

space() {
    local message="$1"

    echo " "
    echo "${message}"
    echo " "
}

error() {
    local error_message="$1"
    echo "${error_message}"
    echo " "
    exit 1 
}

[ -z "$1" ] && print_usage  

while test $# -gt 0; do
    case "$1" in
        -i|--install) i_flag='true'                 && break ;;
        -u|--update) u_flag='true'                  && break ;;
        -r|--run) r_flag='true'                     && break ;;
        -o|--oxide) o_flag='true'                   && break ;;
        -h|--help) print_usage                      && exit 1 ;;
        *) echo "Unknown command." && print_usage   && exit 1 ;;
    esac
done


if [[ $i_flag == 'true' ]] ; then
    space "Installing Rust server."

    mkdir SteamCMD 
    cd SteamCMD 
    wget "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" || error "Failed to download SteamCMD."
    tar -vzxf steamcmd_linux.tar.gz || error "Failed to extract the archive."
    
    ./steamcmd.sh +login anonymous +force_install_dir .. +app_update 258550 validate +quit || error "Installation failed."
    
    cd ..

    space "Installed succesfully."
fi


if [[ $u_flag == 'true' ]] ; then
    space "Updating Rust server."

    cd SteamCMD || error "Seems that server isn't installed, make sure to run ./rs_manager -i before updating."
    ./steamcmd.sh +login anonymous +force_install_dir .. +app_update 258550 validate +quit
    cd ..

    space "Updated succesfully."
fi

exit 0
